/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SupportRouteImport } from './routes/support'
import { Route as PrivacyWordRescueRouteImport } from './routes/privacy_.word-rescue'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsReadTheRoomRouteImport } from './routes/products.read-the-room'
import { Route as PrivacyReadTheRoomEnRouteImport } from './routes/privacy_.read-the-room.en'
import { Route as PrivacyReadTheRoomKoRouteImport } from './routes/privacy_.read-the-room.ko'
import { Route as PrivacySpeakfallEnRouteImport } from './routes/privacy_.speakfall.en'
import { Route as PrivacySpeakfallKoRouteImport } from './routes/privacy_.speakfall.ko'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyWordRescueRoute = PrivacyWordRescueRouteImport.update({
  id: '/privacy_/word-rescue',
  path: '/privacy/word-rescue',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsReadTheRoomRoute = ProductsReadTheRoomRouteImport.update({
  id: '/products/read-the-room',
  path: '/products/read-the-room',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyReadTheRoomEnRoute = PrivacyReadTheRoomEnRouteImport.update({
  id: '/privacy_/read-the-room/en',
  path: '/privacy/read-the-room/en',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyReadTheRoomKoRoute = PrivacyReadTheRoomKoRouteImport.update({
  id: '/privacy_/read-the-room/ko',
  path: '/privacy/read-the-room/ko',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacySpeakfallEnRoute = PrivacySpeakfallEnRouteImport.update({
  id: '/privacy_/speakfall/en',
  path: '/privacy/speakfall/en',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacySpeakfallKoRoute = PrivacySpeakfallKoRouteImport.update({
  id: '/privacy_/speakfall/ko',
  path: '/privacy/speakfall/ko',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/support': typeof SupportRoute
  '/privacy/word-rescue': typeof PrivacyWordRescueRoute
  '/products/read-the-room': typeof ProductsReadTheRoomRoute
  '/products/': typeof ProductsIndexRoute
  '/privacy/read-the-room/en': typeof PrivacyReadTheRoomEnRoute
  '/privacy/read-the-room/ko': typeof PrivacyReadTheRoomKoRoute
  '/privacy/speakfall/en': typeof PrivacySpeakfallEnRoute
  '/privacy/speakfall/ko': typeof PrivacySpeakfallKoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/support': typeof SupportRoute
  '/privacy/word-rescue': typeof PrivacyWordRescueRoute
  '/products/read-the-room': typeof ProductsReadTheRoomRoute
  '/products': typeof ProductsIndexRoute
  '/privacy/read-the-room/en': typeof PrivacyReadTheRoomEnRoute
  '/privacy/read-the-room/ko': typeof PrivacyReadTheRoomKoRoute
  '/privacy/speakfall/en': typeof PrivacySpeakfallEnRoute
  '/privacy/speakfall/ko': typeof PrivacySpeakfallKoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/support': typeof SupportRoute
  '/privacy_/word-rescue': typeof PrivacyWordRescueRoute
  '/products/read-the-room': typeof ProductsReadTheRoomRoute
  '/products/': typeof ProductsIndexRoute
  '/privacy_/read-the-room/en': typeof PrivacyReadTheRoomEnRoute
  '/privacy_/read-the-room/ko': typeof PrivacyReadTheRoomKoRoute
  '/privacy_/speakfall/en': typeof PrivacySpeakfallEnRoute
  '/privacy_/speakfall/ko': typeof PrivacySpeakfallKoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/privacy'
    | '/support'
    | '/privacy/word-rescue'
    | '/products/read-the-room'
    | '/products/'
    | '/privacy/read-the-room/en'
    | '/privacy/read-the-room/ko'
    | '/privacy/speakfall/en'
    | '/privacy/speakfall/ko'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/privacy'
    | '/support'
    | '/privacy/word-rescue'
    | '/products/read-the-room'
    | '/products'
    | '/privacy/read-the-room/en'
    | '/privacy/read-the-room/ko'
    | '/privacy/speakfall/en'
    | '/privacy/speakfall/ko'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/privacy'
    | '/support'
    | '/privacy_/word-rescue'
    | '/products/read-the-room'
    | '/products/'
    | '/privacy_/read-the-room/en'
    | '/privacy_/read-the-room/ko'
    | '/privacy_/speakfall/en'
    | '/privacy_/speakfall/ko'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  SupportRoute: typeof SupportRoute
  PrivacyWordRescueRoute: typeof PrivacyWordRescueRoute
  ProductsReadTheRoomRoute: typeof ProductsReadTheRoomRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  PrivacyReadTheRoomEnRoute: typeof PrivacyReadTheRoomEnRoute
  PrivacyReadTheRoomKoRoute: typeof PrivacyReadTheRoomKoRoute
  PrivacySpeakfallEnRoute: typeof PrivacySpeakfallEnRoute
  PrivacySpeakfallKoRoute: typeof PrivacySpeakfallKoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy_/word-rescue': {
      id: '/privacy_/word-rescue'
      path: '/privacy/word-rescue'
      fullPath: '/privacy/word-rescue'
      preLoaderRoute: typeof PrivacyWordRescueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/read-the-room': {
      id: '/products/read-the-room'
      path: '/products/read-the-room'
      fullPath: '/products/read-the-room'
      preLoaderRoute: typeof ProductsReadTheRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy_/read-the-room/en': {
      id: '/privacy_/read-the-room/en'
      path: '/privacy/read-the-room/en'
      fullPath: '/privacy/read-the-room/en'
      preLoaderRoute: typeof PrivacyReadTheRoomEnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy_/read-the-room/ko': {
      id: '/privacy_/read-the-room/ko'
      path: '/privacy/read-the-room/ko'
      fullPath: '/privacy/read-the-room/ko'
      preLoaderRoute: typeof PrivacyReadTheRoomKoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy_/speakfall/en': {
      id: '/privacy_/speakfall/en'
      path: '/privacy/speakfall/en'
      fullPath: '/privacy/speakfall/en'
      preLoaderRoute: typeof PrivacySpeakfallEnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy_/speakfall/ko': {
      id: '/privacy_/speakfall/ko'
      path: '/privacy/speakfall/ko'
      fullPath: '/privacy/speakfall/ko'
      preLoaderRoute: typeof PrivacySpeakfallKoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  SupportRoute: SupportRoute,
  PrivacyWordRescueRoute: PrivacyWordRescueRoute,
  ProductsReadTheRoomRoute: ProductsReadTheRoomRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  PrivacyReadTheRoomEnRoute: PrivacyReadTheRoomEnRoute,
  PrivacyReadTheRoomKoRoute: PrivacyReadTheRoomKoRoute,
  PrivacySpeakfallEnRoute: PrivacySpeakfallEnRoute,
  PrivacySpeakfallKoRoute: PrivacySpeakfallKoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
